# Copy .env.example to an ignored .env.private and run:
# zed-http examples/widgets.http --name list-widgets --env-file .env.private

# @name list-widgets
GET {{API_BASE_URL}}/widgets
Authorization: Bearer {{API_TOKEN}}
Accept: application/json

###
# @name create-widget
POST {{API_BASE_URL}}/widgets
Authorization: Bearer {{API_TOKEN}}
Content-Type: application/json
Accept: application/json

{
  "name": "example-widget"
}
